/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmCommsMasterSvc.h>
#include "tctlmCubeWheelControlProgram3.h"

/*******************************************************************************
 ***************************  GLOBAL MACROS   **********************************
 ******************************************************************************/

/*******************************************************************************
 **************************   GLOBAL FUNCTIONS   *******************************
 ******************************************************************************/

 /* SET functions */

ErrorCode tctlmCubeWheelControlProgram3_setReset(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Reset *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setReset(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setUnixTime(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogIndex(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogEntry(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setErrorLogClear(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogClear(endpoint);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogSettings(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setConfigPersist(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setConfigPersist(endpoint);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setMotorPower(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_MotorPower *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 60;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->motorPowerSwitch & 0x01) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        bufferSizeUsed = 1;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setBackupGain(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_BackupGain *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 61;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 12)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->kp, sizeof(F32));
        /*************************/
        MEMCPY(&buffer[4], &setVal->ki, sizeof(F32));
        /*************************/
        MEMCPY(&buffer[8], &setVal->kd, sizeof(F32));
        /*************************/
        bufferSizeUsed = 12;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setClearErrors(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 62;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setWheelTorqueRef(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelTorqueRef *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 63;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->torqueRef, sizeof(F32));
        /*************************/
        bufferSizeUsed = 4;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setWheelSpeedRef(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelSpeedRef *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 64;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->speedRef, sizeof(F32));
        /*************************/
        bufferSizeUsed = 4;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setWheelDuty(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelDuty *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 65;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->dutyCycle, sizeof(F32));
        /*************************/
        bufferSizeUsed = 4;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setBackupWheelMode(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_BackupWheelMode *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 66;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->backupMode & 0x01) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        bufferSizeUsed = 1;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setMainGain(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_MainGain *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 67;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 12)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->kp, sizeof(F32));
        /*************************/
        MEMCPY(&buffer[4], &setVal->ki, sizeof(F32));
        /*************************/
        MEMCPY(&buffer[8], &setVal->kd, sizeof(F32));
        /*************************/
        bufferSizeUsed = 12;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setPWMGain(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_PWMGain *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 68;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->k, sizeof(F32));
        /*************************/
        bufferSizeUsed = 4;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setWheelTravelRef(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelTravelRef *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 69;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 8)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->speedRef, sizeof(F32));
        /*************************/
        MEMCPY(&buffer[4], &setVal->distanceRef, sizeof(S32));
        /*************************/
        bufferSizeUsed = 8;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_setWheelRefRampRateLimit(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelRefRampRateLimit *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 70;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->rampRateLimit, sizeof(F32));
        /*************************/
        bufferSizeUsed = 4;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}


 /* GET functions */

ErrorCode tctlmCubeWheelControlProgram3_getIdentification(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getSerialNumber(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_SerialNumber *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getSerialNumber(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogIndex(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogEntry(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogSettings(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getUnixTime(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getConfigPersistDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ConfigPersistDiagnostics *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getConfigPersistDiagnostics(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getCommsStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommsStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommsStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getVersion(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Version *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getVersion(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getBootStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_BootStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getBootStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getTelecommandAcknowledge(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_TelecommandAcknowledge *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getTelecommandAcknowledge(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getCommonErrorCodes(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommonErrorCodes *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommonErrorCodes(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getIdentification2(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification2 *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification2(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelPosData(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelPosData *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 183;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 15)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 15)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelPosition, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelSpeed, &buffer[4], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelReference, &buffer[8], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->batteryCurrent, &buffer[12], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[14], sizeof(U8));
        returnVal->wheelErrorState = (TypesCubeWheelControlProgram3_WheelErrorState)((prepare4 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelModel(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelModel *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 184;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->motorWheelType = (TypesCubeWheelControlProgram3_WheelTypeEnum)((prepare0 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelTorque(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelTorque *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 185;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelTorque, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->wheelErrorState = (TypesCubeWheelControlProgram3_WheelErrorState)((prepare1 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelTorqueRef(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelTorqueRef *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 186;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->torqueRef, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getControlMode(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_ControlMode *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 187;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->controlMode = (TypesCubeWheelControlProgram3_ControlModeVal)((prepare0 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelSpeed(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelSpeed *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 188;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelSpeed, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->wheelErrorState = (TypesCubeWheelControlProgram3_WheelErrorState)((prepare1 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getHealthTlm(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_HealthTlm *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 189;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 17)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 17)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->batteryCurrent, &buffer[0], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->batteryVoltage, &buffer[2], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->driverVoltage, &buffer[4], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->digitalCurrent, &buffer[6], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->mcuTemperature, &buffer[8], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(returnVal->watchdogCount, &buffer[12], 5);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelData(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelData *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 190;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 15)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 15)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelSpeed, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelSpeedBackup, &buffer[4], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->wheelReference, &buffer[8], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->batteryCurrent, &buffer[12], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[14], sizeof(U8));
        returnVal->wheelErrorState = (TypesCubeWheelControlProgram3_WheelErrorState)((prepare4 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getPWMGain(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_PWMGain *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 191;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->k, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getBackupGain(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_BackupGain *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 192;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 12)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 12)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->kp, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->ki, &buffer[4], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->kd, &buffer[8], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getMainGain(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_MainGain *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 193;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 12)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 12)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->kp, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->ki, &buffer[4], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->kd, &buffer[8], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getStatusErrorFlags(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_StatusErrorFlags *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 194;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->invalidTelemetry = (Boolean)((prepare0 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[0], sizeof(U8));
        returnVal->invalidTelecommand = (Boolean)((prepare1 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[0], sizeof(U8));
        returnVal->encoderError = (Boolean)((prepare2 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[0], sizeof(U8));
        returnVal->uARTError = (Boolean)((prepare3 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[0], sizeof(U8));
        returnVal->i2CError = (Boolean)((prepare4 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[0], sizeof(U8));
        returnVal->cANError = (Boolean)((prepare5 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[0], sizeof(U8));
        returnVal->configError = (Boolean)((prepare6 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[0], sizeof(U8));
        returnVal->speedError = (Boolean)((prepare7 >> 7) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelDuty(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelDuty *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 195;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->dutyCycle, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelSpeedRef(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelSpeedRef *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 196;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->speedRef, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getMotorPower(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_MotorPower *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 197;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->motorPowerSwitch = (Boolean)((prepare0 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getBackupWheelMode(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_BackupWheelMode *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 198;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->backupMode = (Boolean)((prepare0 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getStator(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_Stator *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 199;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 8)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 8)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->coilcurrent, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->statortemp, &buffer[4], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeWheelControlProgram3_getWheelRefRampRateLimit(TypeDef_TctlmEndpoint *endpoint, TypesCubeWheelControlProgram3_WheelRefRampRateLimit *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 200;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->rampRateLimit, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

