/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmCommsMasterSvc.h>
#include "tctlmCubeNodeControlProgramPst3sCommon1.h"

/*******************************************************************************
 ***************************  GLOBAL MACROS   **********************************
 ******************************************************************************/

/*******************************************************************************
 **************************   GLOBAL FUNCTIONS   *******************************
 ******************************************************************************/

 /* SET functions */

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sDynamicMode(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sDynamicMode *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 57;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        U8 prepare1 = ((setVal->dynamicMode & 0xFF) << 0);
        MEMCPY(&buffer[1], &prepare1, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sSaaMode(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSaaMode *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 58;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        U8 prepare1 = ((setVal->saaMode & 0xFF) << 0);
        MEMCPY(&buffer[1], &prepare1, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSvcSettings *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 59;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 6)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->maxTcTlmErrors, sizeof(U32));
        /*************************/
        MEMCPY(&buffer[4], &setVal->sampleFrequency, sizeof(U8));
        /*************************/
        U8 prepare5 = ((setVal->autoSample & 0x01) << 0)
                    | ((setVal->apiVersion & 0x7F) << 1);
        MEMCPY(&buffer[5], &prepare5, sizeof(U8));
        /*************************/
        bufferSizeUsed = 6;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sPower(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sPower *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 60;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 12)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->unixTimeSeconds, sizeof(U32));
        /*************************/
        MEMCPY(&buffer[4], &setVal->unixTimeNanoSeconds, sizeof(U32));
        /*************************/
        U8 prepare8 = ((setVal->powerStr[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].power & 0xFF) << 0);
        MEMCPY(&buffer[8], &prepare8, sizeof(U8));
        /*************************/
        U8 prepare9 = ((setVal->powerStr[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].power & 0xFF) << 0);
        MEMCPY(&buffer[9], &prepare9, sizeof(U8));
        /*************************/
        U8 prepare10 = ((setVal->powerStr[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].power & 0xFF) << 0);
        MEMCPY(&buffer[10], &prepare10, sizeof(U8));
        /*************************/
        U8 prepare11 = ((setVal->powerStr[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].power & 0xFF) << 0);
        MEMCPY(&buffer[11], &prepare11, sizeof(U8));
        /*************************/
        bufferSizeUsed = 12;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sQuaternionFiltering(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sQuaternionFiltering *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 61;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        U8 prepare1 = ((setVal->quaternionFiltering & 0xFF) << 0);
        MEMCPY(&buffer[1], &prepare1, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sSecondCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSecondCalibration *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 62;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->unixTime, sizeof(U32));
        /*************************/
        bufferSizeUsed = 5;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sExposure(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sExposure *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 63;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->exposure, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sNumberNavigationStars(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sNumberNavigationStars *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 65;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->numberStars, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sFSST(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sFSST *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 66;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->threshold, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sTrackingModeThreshold(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sTrackingModeThreshold *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 67;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->threshold, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sSystemReset(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSystemReset *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 68;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        bufferSizeUsed = 1;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sImageFixedThreshold(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sImageFixedThreshold *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 69;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->threshold, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setNodeSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_NodeSvcSettings *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 70;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->pst3sAutoBoot & 0x01) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        bufferSizeUsed = 1;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sSaaThreshold(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSaaThreshold *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 71;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 2)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        MEMCPY(&buffer[1], &setVal->saaThreshold, sizeof(U8));
        /*************************/
        bufferSizeUsed = 2;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_setPst3sEdacOff(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sEdacOff *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 72;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->port & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        bufferSizeUsed = 1;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}


 /* GET functions */

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getNodeSvcStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_NodeSvcStatus *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 189;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 17)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 17)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->nodeState = (TypesCubeNodeControlProgramPst3sCommon1_NodeState)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].errorCode, &buffer[1], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].errorCode, &buffer[5], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].errorCode, &buffer[9], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].errorCode, &buffer[13], sizeof(U32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getPst3sConfig1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sConfig1 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 190;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 13)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 13)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->tlm.apiVersion = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sApiVersion)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imageExposure, &buffer[1], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imageThreshold, &buffer[2], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.backGroundValues, &buffer[3], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm.operatingMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sOperatingModes)((prepare4 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imagingGain, &buffer[5], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.minNavigationStars, &buffer[6], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[7], sizeof(U8));
        returnVal->tlm.dynamicMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sDynamicModeEnum)((prepare7 >> 0) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[7], sizeof(U8));
        returnVal->tlm.saaMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sSaaWorkingMode)((prepare8 >> 4) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.saaThreshold, &buffer[8], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare10;
        MEMCPY(&prepare10, &buffer[9], sizeof(U8));
        returnVal->tlm.quaternionFilteringState = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sQFilteringGetState)((prepare10 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.fourStarCaptureThreshold, &buffer[10], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.trackingThreshold, &buffer[11], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[12], sizeof(U8));
        returnVal->tlm.edacSwitch = (Boolean)((prepare13 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getPst3sAttitude1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sAttitude1 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 191;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 43)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 43)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->tlm.apiVersion = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sApiVersion)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat1, &buffer[1], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat2, &buffer[5], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat3, &buffer[9], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat4, &buffer[13], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.angVelX, &buffer[17], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.angVelY, &buffer[21], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.angVelZ, &buffer[25], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[29], sizeof(U8));
        returnVal->tlm.rateQuality = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sRateQuality)((prepare8 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.unixSeconds, &buffer[30], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.unixSecondsDecimal, &buffer[34], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.numberOfExtractedStars, &buffer[38], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[39], sizeof(U8));
        returnVal->tlm.operatingMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sOperatingModes)((prepare12 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[40], sizeof(U8));
        returnVal->tlm.dataValid = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sDataValid)((prepare13 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.identifiedStars, &buffer[41], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[42], sizeof(U8));
        returnVal->tlm.quaternionFilteringState = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sQFilteringGetState)((prepare15 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getPst3sSvcStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSvcStatus *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 192;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 44)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 44)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].state = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sState)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].failCount, &buffer[1], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].failCountLastSuccess, &buffer[5], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[9], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].lastReq = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlms)((prepare3 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[10], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].lastReqResult = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlmResult)((prepare4 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[11], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].state = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sState)((prepare5 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].failCount, &buffer[12], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].failCountLastSuccess, &buffer[16], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[20], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].lastReq = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlms)((prepare8 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare9;
        MEMCPY(&prepare9, &buffer[21], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].lastReqResult = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlmResult)((prepare9 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare10;
        MEMCPY(&prepare10, &buffer[22], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].state = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sState)((prepare10 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].failCount, &buffer[23], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].failCountLastSuccess, &buffer[27], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[31], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].lastReq = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlms)((prepare13 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare14;
        MEMCPY(&prepare14, &buffer[32], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].lastReqResult = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlmResult)((prepare14 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[33], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].state = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sState)((prepare15 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].failCount, &buffer[34], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].failCountLastSuccess, &buffer[38], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare18;
        MEMCPY(&prepare18, &buffer[42], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].lastReq = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlms)((prepare18 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare19;
        MEMCPY(&prepare19, &buffer[43], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].lastReqResult = (TypesCubeNodeControlProgramPst3sCommon1_Pst3sTcTlmResult)((prepare19 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getPst3sTlm1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sTlm1 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 193;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 63)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 63)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->tlm.apiVersion = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sApiVersion)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat1, &buffer[1], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat2, &buffer[5], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat3, &buffer[9], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.quat4, &buffer[13], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.angVelX, &buffer[17], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.angVelY, &buffer[21], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.angVelZ, &buffer[25], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[29], sizeof(U8));
        returnVal->tlm.rateQuality = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sRateQuality)((prepare8 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.unixSeconds, &buffer[30], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.unixSecondsDecimal, &buffer[34], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.temperature, &buffer[38], sizeof(S8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imageExposure, &buffer[39], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imageThreshold, &buffer[40], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.backGroundValues, &buffer[41], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.internalProcessCode, &buffer[42], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare16;
        MEMCPY(&prepare16, &buffer[43], sizeof(U8));
        returnVal->tlm.cmosChipIdResult = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sSelfTestResult)((prepare16 >> 0) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare17;
        MEMCPY(&prepare17, &buffer[43], sizeof(U8));
        returnVal->tlm.fpgaMRamResult = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sSelfTestResult)((prepare17 >> 4) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.numberOfExtractedStars, &buffer[44], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare19;
        MEMCPY(&prepare19, &buffer[45], sizeof(U8));
        returnVal->tlm.operatingMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sOperatingModes)((prepare19 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imagingGain, &buffer[46], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.minNavigationStars, &buffer[47], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare22;
        MEMCPY(&prepare22, &buffer[48], sizeof(U8));
        returnVal->tlm.dataValid = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sDataValid)((prepare22 >> 0) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare23;
        MEMCPY(&prepare23, &buffer[48], sizeof(U8));
        returnVal->tlm.extImageState = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sExtImageState)((prepare23 >> 4) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.identifiedStars, &buffer[49], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceNumber, &buffer[50], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.softwareVersion, &buffer[51], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.edacErrorCount, &buffer[52], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imageFrameNumber, &buffer[53], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare29;
        MEMCPY(&prepare29, &buffer[57], sizeof(U8));
        returnVal->tlm.dynamicMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sDynamicModeEnum)((prepare29 >> 0) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare30;
        MEMCPY(&prepare30, &buffer[57], sizeof(U8));
        returnVal->tlm.saaMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sSaaWorkingMode)((prepare30 >> 4) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.saaThreshold, &buffer[58], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare32;
        MEMCPY(&prepare32, &buffer[59], sizeof(U8));
        returnVal->tlm.quaternionFilteringState = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sQFilteringGetState)((prepare32 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.fourStarCaptureThreshold, &buffer[60], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.trackingThreshold, &buffer[61], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare35;
        MEMCPY(&prepare35, &buffer[62], sizeof(U8));
        returnVal->tlm.edacSwitch = (Boolean)((prepare35 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getPst3sHousekeeping1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sHousekeeping1 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 194;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 15)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 15)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->tlm.apiVersion = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sApiVersion)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.temperature, &buffer[1], sizeof(S8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.backGroundValues, &buffer[2], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.internalProcessCode, &buffer[3], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm.cmosChipIdResult = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sSelfTestResult)((prepare4 >> 0) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[4], sizeof(U8));
        returnVal->tlm.fpgaMRamResult = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sSelfTestResult)((prepare5 >> 4) & 0x0F);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[5], sizeof(U8));
        returnVal->tlm.operatingMode = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sOperatingModes)((prepare6 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[6], sizeof(U8));
        returnVal->tlm.extImageState = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sExtImageState)((prepare7 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceNumber, &buffer[7], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.softwareVerion, &buffer[8], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.edacErrorCount, &buffer[9], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.imageFrameNumber, &buffer[10], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[14], sizeof(U8));
        returnVal->tlm.quaternionFilteringState = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sQFilteringGetState)((prepare12 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getPst3sSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_Pst3sSvcSettings *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 195;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 6)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 6)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->maxTcTlmErrors, &buffer[0], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->sampleFrequency, &buffer[4], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[5], sizeof(U8));
        returnVal->autoSample = (Boolean)((prepare2 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[5], sizeof(U8));
        returnVal->apiVersion = (TypesCubeNodeControlProgramPst3sCommonTypes1_Pst3sApiVersion)((prepare3 >> 1) & 0x7F);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramPst3sCommon1_getNodeSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramPst3sCommon1_NodeSvcSettings *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 196;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->pst3sAutoBoot = (Boolean)((prepare0 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

