/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmCommsMasterSvc.h>
#include "tctlmCubeNodeControlProgramLitefufors1.h"

/*******************************************************************************
 ***************************  GLOBAL MACROS   **********************************
 ******************************************************************************/

/*******************************************************************************
 **************************   GLOBAL FUNCTIONS   *******************************
 ******************************************************************************/

 /* SET functions */

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setReset(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Reset *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setReset(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setUnixTime(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogIndex(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogEntry(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setErrorLogClear(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogClear(endpoint);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogSettings(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setConfigPersist(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setConfigPersist(endpoint);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setUforsSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsSvcSettings *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 67;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 7)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&buffer[0], &setVal->maxReqErrors, sizeof(U32));
        /*************************/
        MEMCPY(&buffer[4], &setVal->sampleFrequency, sizeof(U16));
        /*************************/
        U8 prepare6 = ((setVal->autoSample & 0x01) << 0);
        MEMCPY(&buffer[6], &prepare6, sizeof(U8));
        /*************************/
        bufferSizeUsed = 7;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setUforsPower(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsPower *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 68;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->powerUfors[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].power & 0xFF) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        U8 prepare1 = ((setVal->powerUfors[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].power & 0xFF) << 0);
        MEMCPY(&buffer[1], &prepare1, sizeof(U8));
        /*************************/
        U8 prepare2 = ((setVal->powerUfors[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].power & 0xFF) << 0);
        MEMCPY(&buffer[2], &prepare2, sizeof(U8));
        /*************************/
        U8 prepare3 = ((setVal->powerUfors[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].power & 0xFF) << 0);
        MEMCPY(&buffer[3], &prepare3, sizeof(U8));
        /*************************/
        bufferSizeUsed = 4;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setNodeSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_NodeSvcSettings *setVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 69;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0 = ((setVal->uforsAutoBoot & 0x01) << 0);
        MEMCPY(&buffer[0], &prepare0, sizeof(U8));
        /*************************/
        bufferSizeUsed = 1;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_setPowerSwitchState(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_PowerSwitchState *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_setPowerSwitchState(endpoint, setVal);

    return result;
}


 /* GET functions */

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getIdentification(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getSerialNumber(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_SerialNumber *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getSerialNumber(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogIndex(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogEntry(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogSettings(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getUnixTime(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getConfigPersistDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ConfigPersistDiagnostics *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getConfigPersistDiagnostics(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getCommsStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommsStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommsStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getVersion(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Version *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getVersion(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getBootStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_BootStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getBootStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getTelecommandAcknowledge(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_TelecommandAcknowledge *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getTelecommandAcknowledge(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getCommonErrorCodes(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommonErrorCodes *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommonErrorCodes(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getIdentification2(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification2 *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification2(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsTlmPort4(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsTlmPort4 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 188;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rate, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->tlm.nogo = (Boolean)((prepare1 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[4], sizeof(U8));
        returnVal->tlm.rstAck = (Boolean)((prepare2 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[4], sizeof(U8));
        returnVal->tlm.tempWarn = (Boolean)((prepare3 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm.auxControlLoopErr = (Boolean)((prepare4 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[4], sizeof(U8));
        returnVal->tlm.hardBitErr = (Boolean)((prepare5 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[4], sizeof(U8));
        returnVal->tlm.measRangeErr = (Boolean)((prepare6 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[4], sizeof(U8));
        returnVal->tlm.unknwnCmd = (Boolean)((prepare7 >> 6) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsTlmPort2(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsTlmPort2 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 189;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rate, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->tlm.nogo = (Boolean)((prepare1 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[4], sizeof(U8));
        returnVal->tlm.rstAck = (Boolean)((prepare2 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[4], sizeof(U8));
        returnVal->tlm.tempWarn = (Boolean)((prepare3 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm.auxControlLoopErr = (Boolean)((prepare4 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[4], sizeof(U8));
        returnVal->tlm.hardBitErr = (Boolean)((prepare5 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[4], sizeof(U8));
        returnVal->tlm.measRangeErr = (Boolean)((prepare6 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[4], sizeof(U8));
        returnVal->tlm.unknwnCmd = (Boolean)((prepare7 >> 6) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsTlm(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsTlm *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 190;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 20)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 20)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].rate, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].nogo = (Boolean)((prepare1 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].rstAck = (Boolean)((prepare2 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].tempWarn = (Boolean)((prepare3 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].auxControlLoopErr = (Boolean)((prepare4 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].hardBitErr = (Boolean)((prepare5 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].measRangeErr = (Boolean)((prepare6 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[4], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].unknwnCmd = (Boolean)((prepare7 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].rate, &buffer[5], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare10;
        MEMCPY(&prepare10, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].nogo = (Boolean)((prepare10 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare11;
        MEMCPY(&prepare11, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].rstAck = (Boolean)((prepare11 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].tempWarn = (Boolean)((prepare12 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].auxControlLoopErr = (Boolean)((prepare13 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare14;
        MEMCPY(&prepare14, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].hardBitErr = (Boolean)((prepare14 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].measRangeErr = (Boolean)((prepare15 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare16;
        MEMCPY(&prepare16, &buffer[9], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].unknwnCmd = (Boolean)((prepare16 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].rate, &buffer[10], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare19;
        MEMCPY(&prepare19, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].nogo = (Boolean)((prepare19 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare20;
        MEMCPY(&prepare20, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].rstAck = (Boolean)((prepare20 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare21;
        MEMCPY(&prepare21, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].tempWarn = (Boolean)((prepare21 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare22;
        MEMCPY(&prepare22, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].auxControlLoopErr = (Boolean)((prepare22 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare23;
        MEMCPY(&prepare23, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].hardBitErr = (Boolean)((prepare23 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare24;
        MEMCPY(&prepare24, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].measRangeErr = (Boolean)((prepare24 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare25;
        MEMCPY(&prepare25, &buffer[14], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].unknwnCmd = (Boolean)((prepare25 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].rate, &buffer[15], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare28;
        MEMCPY(&prepare28, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].nogo = (Boolean)((prepare28 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare29;
        MEMCPY(&prepare29, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].rstAck = (Boolean)((prepare29 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare30;
        MEMCPY(&prepare30, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].tempWarn = (Boolean)((prepare30 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare31;
        MEMCPY(&prepare31, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].auxControlLoopErr = (Boolean)((prepare31 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare32;
        MEMCPY(&prepare32, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].hardBitErr = (Boolean)((prepare32 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare33;
        MEMCPY(&prepare33, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].measRangeErr = (Boolean)((prepare33 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare34;
        MEMCPY(&prepare34, &buffer[19], sizeof(U8));
        returnVal->tlm[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].unknwnCmd = (Boolean)((prepare34 >> 6) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getNodeSvcStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_NodeSvcStatus *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 191;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 17)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 17)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->nodeState = (TypesCubeNodeControlProgramLitefufors1_NodeState)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].errorCode, &buffer[1], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].errorCode, &buffer[5], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].errorCode, &buffer[9], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->bootError[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].errorCode, &buffer[13], sizeof(U32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getNodeSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_NodeSvcSettings *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 192;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 1)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 1)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->uforsAutoBoot = (Boolean)((prepare0 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsSvcSettings *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 193;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 7)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 7)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->maxReqErrors, &buffer[0], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->sampleFrequency, &buffer[4], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[6], sizeof(U8));
        returnVal->autoSample = (Boolean)((prepare2 >> 0) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsSvcStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsSvcStatus *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 194;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 40)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 40)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare0;
        MEMCPY(&prepare0, &buffer[0], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].state = (TypesCubeNodeControlProgramLitefufors1_UforsState)((prepare0 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].failCount, &buffer[1], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].failCountLastSuccess, &buffer[5], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[9], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_1].lastReqResult = (TypesCubeNodeControlProgramLitefufors1_UforsReqResult)((prepare3 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[10], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].state = (TypesCubeNodeControlProgramLitefufors1_UforsState)((prepare4 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].failCount, &buffer[11], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].failCountLastSuccess, &buffer[15], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[19], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_2].lastReqResult = (TypesCubeNodeControlProgramLitefufors1_UforsReqResult)((prepare7 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[20], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].state = (TypesCubeNodeControlProgramLitefufors1_UforsState)((prepare8 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].failCount, &buffer[21], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].failCountLastSuccess, &buffer[25], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare11;
        MEMCPY(&prepare11, &buffer[29], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_3].lastReqResult = (TypesCubeNodeControlProgramLitefufors1_UforsReqResult)((prepare11 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[30], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].state = (TypesCubeNodeControlProgramLitefufors1_UforsState)((prepare12 >> 0) & 0xFF);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].failCount, &buffer[31], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].failCountLastSuccess, &buffer[35], sizeof(U32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[39], sizeof(U8));
        returnVal->status[TYPES_CUBE_NODE_COMMON_TYPES_1__PORT_4].lastReqResult = (TypesCubeNodeControlProgramLitefufors1_UforsReqResult)((prepare15 >> 0) & 0xFF);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsTlmPort1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsTlmPort1 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 195;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rate, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->tlm.nogo = (Boolean)((prepare1 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[4], sizeof(U8));
        returnVal->tlm.rstAck = (Boolean)((prepare2 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[4], sizeof(U8));
        returnVal->tlm.tempWarn = (Boolean)((prepare3 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm.auxControlLoopErr = (Boolean)((prepare4 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[4], sizeof(U8));
        returnVal->tlm.hardBitErr = (Boolean)((prepare5 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[4], sizeof(U8));
        returnVal->tlm.measRangeErr = (Boolean)((prepare6 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[4], sizeof(U8));
        returnVal->tlm.unknwnCmd = (Boolean)((prepare7 >> 6) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getUforsTlmPort3(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramLitefufors1_UforsTlmPort3 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 196;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rate, &buffer[0], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare1;
        MEMCPY(&prepare1, &buffer[4], sizeof(U8));
        returnVal->tlm.nogo = (Boolean)((prepare1 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare2;
        MEMCPY(&prepare2, &buffer[4], sizeof(U8));
        returnVal->tlm.rstAck = (Boolean)((prepare2 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare3;
        MEMCPY(&prepare3, &buffer[4], sizeof(U8));
        returnVal->tlm.tempWarn = (Boolean)((prepare3 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare4;
        MEMCPY(&prepare4, &buffer[4], sizeof(U8));
        returnVal->tlm.auxControlLoopErr = (Boolean)((prepare4 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare5;
        MEMCPY(&prepare5, &buffer[4], sizeof(U8));
        returnVal->tlm.hardBitErr = (Boolean)((prepare5 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[4], sizeof(U8));
        returnVal->tlm.measRangeErr = (Boolean)((prepare6 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[4], sizeof(U8));
        returnVal->tlm.unknwnCmd = (Boolean)((prepare7 >> 6) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getNodeModel(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_NodeModel *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_getNodeModel(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getPowerSwitchState(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_PowerSwitchState *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_getPowerSwitchState(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramLitefufors1_getHealthTlm(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_HealthTlm *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_getHealthTlm(endpoint, returnVal);

    return result;
}

