/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#ifndef TCTLM_CUBE_MAG_CONTROL_PROGRAM_DEPLOY_1__H
#define TCTLM_CUBE_MAG_CONTROL_PROGRAM_DEPLOY_1__H

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmDef.h>

#include "typesCubeMagControlProgramDeploy1.h"
#include "typesCommonFrameworkTypes1.h"
#include "typesCubeMagControlProgramCommonTypes1.h"
#include "tctlmCommonFramework1.h"
#include "tctlmCubeMagControlProgramCommon1.h"

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 *******************************   DEFINES   ***********************************
 ******************************************************************************/

/*******************************************************************************
 *******************************   TYPEDEFS  ***********************************
 ******************************************************************************/

/*******************************************************************************
 *****************************   PROTOTYPES   **********************************
 ******************************************************************************/

 /* SET function prototypes */

/**
 * @brief ID 1, Reset
 * @details Perform a soft reset
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setReset(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Reset *setVal);

/**
 * @brief ID 2, Current Unix time
 * @details Current Unix time
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *setVal);

/**
 * @brief ID 3, Error Log Index
 * @details Describes the index of the error log that will be read when calling GetErrorLogEntry
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *setVal);

/**
 * @brief ID 4, Error Log Entry
 * @details Error Log Entry
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *setVal);

/**
 * @brief ID 5, Error Log Clear
 * @details Clear the Error Log
 *
 * @param[in] endpoint Node endpoint location
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setErrorLogClear(TypeDef_TctlmEndpoint *endpoint);

/**
 * @brief ID 6, Error Log Settings
 * @details Error Log Settings
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *setVal);

/**
 * @brief ID 7, Persist Config
 * @details Writes volatile config items to flash
 *
 * @param[in] endpoint Node endpoint location
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setConfigPersist(TypeDef_TctlmEndpoint *endpoint);

/**
 * @brief ID 60, CubeMag Config
 * @details CubeMag Config Items
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_Config *setVal);

/**
 * @brief ID 61, MMC Magnetometer Config
 * @details MMC Magnetometer Specific Config
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setMmcConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcConfig *setVal);

/**
 * @brief ID 62, PNI Calibration Parameters
 * @details PNI Magnetometer Calibration Parameters
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setPniCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_PniCalibration *setVal);

/**
 * @brief ID 63, Deploy
 * @details Deploy CubeMag
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setDeploy(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_Deploy *setVal);

/**
 * @brief ID 64, PNI Magnetometer Config
 * @details PNI Magnetometer Specific Config
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setPniConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_PniConfig *setVal);

/**
 * @brief ID 65, Sample Redundant
 * @details Trigger a single Sample the Redundant Magnetometer (auto-sample == OFF)
 *
 * @param[in] endpoint Node endpoint location
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setSampleRed(TypeDef_TctlmEndpoint *endpoint);

/**
 * @brief ID 66, Arm Deploy
 * @details Arm CubeMag for Deployment
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setDeployArm(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_DeployArm *setVal);

/**
 * @brief ID 67, Sample Primary
 * @details Trigger a single Sample the Primary Magnetometer (auto-sample == OFF)
 *
 * @param[in] endpoint Node endpoint location
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setSamplePrimary(TypeDef_TctlmEndpoint *endpoint);

/**
 * @brief ID 68, MMC Calibration Parameters
 * @details MMC Magnetometer Calibration Parameters
 *
 * @param[in] endpoint Node endpoint location
 * @param[in] setVal Value Written
 *
 * @return ErrorCode ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_setMmcCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcCalibration *setVal);


 /* GET function prototypes */

/**
 * @brief ID 128, Identification
 * @details Identification information for this node (Legacy definition - use Identification2 instead)
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getIdentification(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification *returnVal);

/**
 * @brief ID 129, Serial Number
 * @details Unique serial number of the CubeSpace Component
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getSerialNumber(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_SerialNumber *returnVal);

/**
 * @brief ID 130, Error Log Index
 * @details Describes the index of the error log that will be read when calling GetErrorLogEntry
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *returnVal);

/**
 * @brief ID 131, Error Log Entry
 * @details Error Log Entry
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *returnVal);

/**
 * @brief ID 132, Error Log Settings
 * @details Error Log Settings
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *returnVal);

/**
 * @brief ID 133, Current Unix time
 * @details Current Unix time
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *returnVal);

/**
 * @brief ID 134, Persist Config Diagnostics
 * @details Diagnostics data for config persistence
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getConfigPersistDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ConfigPersistDiagnostics *returnVal);

/**
 * @brief ID 135, Communication Status
 * @details Communication Status
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getCommsStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommsStatus *returnVal);

/**
 * @brief ID 136, Version
 * @details Firmware Version
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getVersion(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Version *returnVal);

/**
 * @brief ID 137, Boot Status
 * @details State information about the device boot process
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getBootStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_BootStatus *returnVal);

/**
 * @brief ID 138, Telecommand Acknowledge
 * @details Used with the I2C protocol to receive Telecommand Ack/Nack
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getTelecommandAcknowledge(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_TelecommandAcknowledge *returnVal);

/**
 * @brief ID 139, Common Error Codes
 * @details Error codes common to all applications
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getCommonErrorCodes(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommonErrorCodes *returnVal);

/**
 * @brief ID 140, Identification2
 * @details Identification information for this node
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getIdentification2(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification2 *returnVal);

/**
 * @brief ID 185, MMC Calibration Parameters
 * @details MMC Magnetometer Calibration Parameters
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getMmcCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcCalibration *returnVal);

/**
 * @brief ID 186, CubeMag Config
 * @details CubeMag Config Items
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_Config *returnVal);

/**
 * @brief ID 187, Primary Magnetometer Measurement Raw
 * @details Unfiltered last Primary Magnetometer Measurement
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getPrimaryMagMeasurementRaw(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagMeasurementRaw *returnVal);

/**
 * @brief ID 188, State
 * @details All Service States
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getState(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_State *returnVal);

/**
 * @brief ID 189, PNI Calibration Parameters
 * @details PNI Magnetometer Calibration Parameters
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getPniCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_PniCalibration *returnVal);

/**
 * @brief ID 190, Deployment Status
 * @details Deployment Status. Only Applicable to CubeMag Deploy type
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getDeploymentStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_DeploymentStatus *returnVal);

/**
 * @brief ID 191, Redundant Magnetometer Measurement Raw
 * @details Unfiltered last Redundant Magnetometer Measurement
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getRedMagMeasurementRaw(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_RedMagMeasurementRaw *returnVal);

/**
 * @brief ID 192, PNI Magnetometer Config
 * @details PNI Magnetometer Specific Config
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getPniConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_PniConfig *returnVal);

/**
 * @brief ID 193, Redundant Magnetometer Measurement
 * @details Redundant Magnetometer Measurement
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getRedMagMeasurement(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_RedMagMeasurement *returnVal);

/**
 * @brief ID 194, Redundant Magnetometer Temperature
 * @details Redundant Magnetometer Measurement
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getRedMagTemp(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_RedMagTemp *returnVal);

/**
 * @brief ID 195, Redundant Magnetometer Diagnostics
 * @details Redundant Magnetometer Diagnostics
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getRedMagDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_RedMagDiagnostics *returnVal);

/**
 * @brief ID 196, MMC Magnetometer Config
 * @details MMC Magnetometer Specific Config
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getMmcConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcConfig *returnVal);

/**
 * @brief ID 197, Primary Magnetometer Measurement
 * @details Primary Magnetometer Measurement
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getPrimaryMagMeasurement(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagMeasurement *returnVal);

/**
 * @brief ID 198, Primary Magnetometer Temperature
 * @details Main Magnetometer Measurement
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getPrimaryMagTemp(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagTemp *returnVal);

/**
 * @brief ID 199, Primary Magnetometer Diagnostics
 * @details Primary Magnetometer Diagnostics
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getPrimaryMagDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagDiagnostics *returnVal);

/**
 * @brief ID 254, Health Telemetry
 * @details Health Telemetry for CubeMagDeploy
 *
 * @param[in] endpoint Node endpoint location
 * @param[out] returnVal Value Returned
 *
 * @return ErrorCode TCTLM__ERROR_OK on success
 */
ErrorCode tctlmCubeMagControlProgramDeploy1_getHealthTlm(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramDeploy1_HealthTlm *returnVal);


#ifdef __cplusplus
}
#endif

#endif // TCTLM_CUBE_MAG_CONTROL_PROGRAM_DEPLOY_1_H
