/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmCommsMasterSvc.h>
#include "tctlmCubeMagControlProgramCompact1.h"

/*******************************************************************************
 ***************************  GLOBAL MACROS   **********************************
 ******************************************************************************/

/*******************************************************************************
 **************************   GLOBAL FUNCTIONS   *******************************
 ******************************************************************************/

 /* SET functions */

ErrorCode tctlmCubeMagControlProgramCompact1_setReset(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Reset *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setReset(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setUnixTime(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogIndex(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogEntry(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setErrorLogClear(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogClear(endpoint);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogSettings(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setConfigPersist(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setConfigPersist(endpoint);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_Config *setVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_setConfig(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setMmcConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcConfig *setVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_setMmcConfig(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setSamplePrimary(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_setSamplePrimary(endpoint);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_setMmcCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcCalibration *setVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_setMmcCalibration(endpoint, setVal);

    return result;
}


 /* GET functions */

ErrorCode tctlmCubeMagControlProgramCompact1_getIdentification(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getSerialNumber(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_SerialNumber *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getSerialNumber(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogIndex(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogEntry(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogSettings(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getUnixTime(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getConfigPersistDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ConfigPersistDiagnostics *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getConfigPersistDiagnostics(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getCommsStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommsStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommsStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getVersion(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Version *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getVersion(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getBootStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_BootStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getBootStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getTelecommandAcknowledge(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_TelecommandAcknowledge *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getTelecommandAcknowledge(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getCommonErrorCodes(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommonErrorCodes *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommonErrorCodes(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getIdentification2(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification2 *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification2(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getMmcCalibration(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcCalibration *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getMmcCalibration(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_Config *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getConfig(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getPrimaryMagMeasurementRaw(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagMeasurementRaw *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getPrimaryMagMeasurementRaw(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getState(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_State *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getState(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getMmcConfig(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_MmcConfig *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getMmcConfig(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getPrimaryMagMeasurement(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagMeasurement *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getPrimaryMagMeasurement(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getPrimaryMagTemp(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagTemp *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getPrimaryMagTemp(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getPrimaryMagDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCommon1_PrimaryMagDiagnostics *returnVal)
{
    ErrorCode result;

    result = tctlmCubeMagControlProgramCommon1_getPrimaryMagDiagnostics(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeMagControlProgramCompact1_getHealthTlm(TypeDef_TctlmEndpoint *endpoint, TypesCubeMagControlProgramCompact1_HealthTlm *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 254;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 15)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 15)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->mcuCurrent, &buffer[0], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->mcuTemp, &buffer[2], sizeof(S16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->mcuVoltage, &buffer[4], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->magTemp, &buffer[6], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(returnVal->watchdogCount, &buffer[10], 5);
    }
    /*************************/

    return result;
}

