/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmCommsMasterSvc.h>
#include "tctlmCubeNodeControlProgramNssrwlQuad1.h"

/*******************************************************************************
 ***************************  GLOBAL MACROS   **********************************
 ******************************************************************************/

/*******************************************************************************
 **************************   GLOBAL FUNCTIONS   *******************************
 ******************************************************************************/

 /* SET functions */

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setReset(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Reset *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setReset(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setUnixTime(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogIndex(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogEntry(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setErrorLogClear(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogClear(endpoint);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *setVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setErrorLogSettings(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setConfigPersist(TypeDef_TctlmEndpoint *endpoint)
{
    ErrorCode result;

    result = tctlmCommonFramework1_setConfigPersist(endpoint);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNssRwlSoftwareReset(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlSoftwareReset *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNssRwlSoftwareReset(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNssRwlTorque(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlTorque *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNssRwlTorque(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNssRwlPower(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlPower *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNssRwlPower(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNodeSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NodeSvcSettings *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNodeSvcSettings(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNssRwlSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlSvcSettings *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNssRwlSvcSettings(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNssRwlWheelSpeedRef(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlWheelSpeedRef *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNssRwlWheelSpeedRef(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setNssRwlMotorCurrent(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlMotorCurrent *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_setNssRwlMotorCurrent(endpoint, setVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_setPowerSwitchState(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_PowerSwitchState *setVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_setPowerSwitchState(endpoint, setVal);

    return result;
}


 /* GET functions */

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getIdentification(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getSerialNumber(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_SerialNumber *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getSerialNumber(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getErrorLogIndex(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogIndex *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogIndex(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getErrorLogEntry(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogEntry *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogEntry(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getErrorLogSettings(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ErrorLogSettings *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getErrorLogSettings(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getUnixTime(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_UnixTime *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getUnixTime(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getConfigPersistDiagnostics(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_ConfigPersistDiagnostics *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getConfigPersistDiagnostics(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getCommsStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommsStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommsStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getVersion(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Version *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getVersion(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getBootStatus(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_BootStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getBootStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getTelecommandAcknowledge(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_TelecommandAcknowledge *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getTelecommandAcknowledge(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getCommonErrorCodes(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_CommonErrorCodes *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getCommonErrorCodes(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getIdentification2(TypeDef_TctlmEndpoint *endpoint, TypesCommonFramework1_Identification2 *returnVal)
{
    ErrorCode result;

    result = tctlmCommonFramework1_getIdentification2(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlWheelSpeedAll(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlWheelSpeedAll *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlWheelSpeedAll(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmSystem3(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmSystem3 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 183;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 23)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 23)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceType, &buffer[1], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceId, &buffer[2], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.month, &buffer[3], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.year, &buffer[4], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.statusRegister, &buffer[5], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsRegister, &buffer[7], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.systemRegister, &buffer[9], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rwaRegister, &buffer[11], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.gyroRegister, &buffer[13], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.bootFlag, &buffer[14], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.bootVector, &buffer[16], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsControlInterval, &buffer[18], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsStartAddr, &buffer[19], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.tachoStartAddr, &buffer[21], sizeof(U16));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmSystem1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlTlmSystem1 *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlTlmSystem1(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmExtended3(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmExtended3 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 185;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualWheelSpeed, &buffer[1], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmExtended1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlTlmExtended1 *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlTlmExtended1(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmStandard3(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmStandard3 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 187;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 23)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 23)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.targetValue, &buffer[1], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualWheelSpeed, &buffer[5], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualMotorCurrent, &buffer[9], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.temperature, &buffer[13], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.iSignal, &buffer[17], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[21], sizeof(U8));
        returnVal->tlm.reactionWheelMode = (Boolean)((prepare6 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[21], sizeof(U8));
        returnVal->tlm.currentControlMode = (Boolean)((prepare7 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[21], sizeof(U8));
        returnVal->tlm.speedControlMode = (Boolean)((prepare8 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare9;
        MEMCPY(&prepare9, &buffer[21], sizeof(U8));
        returnVal->tlm.torqueMode = (Boolean)((prepare9 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare10;
        MEMCPY(&prepare10, &buffer[21], sizeof(U8));
        returnVal->tlm.wheelGyroMode = (Boolean)((prepare10 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare11;
        MEMCPY(&prepare11, &buffer[21], sizeof(U8));
        returnVal->tlm.omegaPiControlLoop = (Boolean)((prepare11 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[21], sizeof(U8));
        returnVal->tlm.anglePdControlLoop = (Boolean)((prepare12 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[21], sizeof(U8));
        returnVal->tlm.bootControl = (Boolean)((prepare13 >> 7) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare14;
        MEMCPY(&prepare14, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroConnected = (Boolean)((prepare14 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroTelemetry = (Boolean)((prepare15 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare16;
        MEMCPY(&prepare16, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroFlagRegister = (Boolean)((prepare16 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare17;
        MEMCPY(&prepare17, &buffer[22], sizeof(U8));
        returnVal->tlm.crcError = (Boolean)((prepare17 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare18;
        MEMCPY(&prepare18, &buffer[22], sizeof(U8));
        returnVal->tlm.wrongLlCommand = (Boolean)((prepare18 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare19;
        MEMCPY(&prepare19, &buffer[22], sizeof(U8));
        returnVal->tlm.wrongHlCommand = (Boolean)((prepare19 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare20;
        MEMCPY(&prepare20, &buffer[22], sizeof(U8));
        returnVal->tlm.toutSci1Main = (Boolean)((prepare20 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare21;
        MEMCPY(&prepare21, &buffer[22], sizeof(U8));
        returnVal->tlm.toutSci2Gyro = (Boolean)((prepare21 >> 7) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmStandard1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlTlmStandard1 *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlTlmStandard1(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlWheelSpeed3(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlWheelSpeed3 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 189;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->speed.speed, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlWheelSpeed1(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlWheelSpeed1 *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlWheelSpeed1(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlSvcSettings *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlSvcSettings(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNodeSvcSettings(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NodeSvcSettings *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNodeSvcSettings(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNodeSvcStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NodeSvcStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNodeSvcStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlSvcStatus(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlCommon1_NssRwlSvcStatus *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeControlProgramNssrwlCommon1_getNssRwlSvcStatus(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlWheelSpeed2(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlWheelSpeed2 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 195;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->speed.speed, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlWheelSpeed4(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlWheelSpeed4 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 196;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 4)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 4)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->speed.speed, &buffer[0], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmStandard2(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmStandard2 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 197;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 23)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 23)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.targetValue, &buffer[1], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualWheelSpeed, &buffer[5], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualMotorCurrent, &buffer[9], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.temperature, &buffer[13], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.iSignal, &buffer[17], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[21], sizeof(U8));
        returnVal->tlm.reactionWheelMode = (Boolean)((prepare6 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[21], sizeof(U8));
        returnVal->tlm.currentControlMode = (Boolean)((prepare7 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[21], sizeof(U8));
        returnVal->tlm.speedControlMode = (Boolean)((prepare8 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare9;
        MEMCPY(&prepare9, &buffer[21], sizeof(U8));
        returnVal->tlm.torqueMode = (Boolean)((prepare9 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare10;
        MEMCPY(&prepare10, &buffer[21], sizeof(U8));
        returnVal->tlm.wheelGyroMode = (Boolean)((prepare10 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare11;
        MEMCPY(&prepare11, &buffer[21], sizeof(U8));
        returnVal->tlm.omegaPiControlLoop = (Boolean)((prepare11 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[21], sizeof(U8));
        returnVal->tlm.anglePdControlLoop = (Boolean)((prepare12 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[21], sizeof(U8));
        returnVal->tlm.bootControl = (Boolean)((prepare13 >> 7) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare14;
        MEMCPY(&prepare14, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroConnected = (Boolean)((prepare14 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroTelemetry = (Boolean)((prepare15 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare16;
        MEMCPY(&prepare16, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroFlagRegister = (Boolean)((prepare16 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare17;
        MEMCPY(&prepare17, &buffer[22], sizeof(U8));
        returnVal->tlm.crcError = (Boolean)((prepare17 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare18;
        MEMCPY(&prepare18, &buffer[22], sizeof(U8));
        returnVal->tlm.wrongLlCommand = (Boolean)((prepare18 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare19;
        MEMCPY(&prepare19, &buffer[22], sizeof(U8));
        returnVal->tlm.wrongHlCommand = (Boolean)((prepare19 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare20;
        MEMCPY(&prepare20, &buffer[22], sizeof(U8));
        returnVal->tlm.toutSci1Main = (Boolean)((prepare20 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare21;
        MEMCPY(&prepare21, &buffer[22], sizeof(U8));
        returnVal->tlm.toutSci2Gyro = (Boolean)((prepare21 >> 7) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmStandard4(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmStandard4 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 198;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 23)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 23)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.targetValue, &buffer[1], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualWheelSpeed, &buffer[5], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualMotorCurrent, &buffer[9], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.temperature, &buffer[13], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.iSignal, &buffer[17], sizeof(F32));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare6;
        MEMCPY(&prepare6, &buffer[21], sizeof(U8));
        returnVal->tlm.reactionWheelMode = (Boolean)((prepare6 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare7;
        MEMCPY(&prepare7, &buffer[21], sizeof(U8));
        returnVal->tlm.currentControlMode = (Boolean)((prepare7 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare8;
        MEMCPY(&prepare8, &buffer[21], sizeof(U8));
        returnVal->tlm.speedControlMode = (Boolean)((prepare8 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare9;
        MEMCPY(&prepare9, &buffer[21], sizeof(U8));
        returnVal->tlm.torqueMode = (Boolean)((prepare9 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare10;
        MEMCPY(&prepare10, &buffer[21], sizeof(U8));
        returnVal->tlm.wheelGyroMode = (Boolean)((prepare10 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare11;
        MEMCPY(&prepare11, &buffer[21], sizeof(U8));
        returnVal->tlm.omegaPiControlLoop = (Boolean)((prepare11 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare12;
        MEMCPY(&prepare12, &buffer[21], sizeof(U8));
        returnVal->tlm.anglePdControlLoop = (Boolean)((prepare12 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare13;
        MEMCPY(&prepare13, &buffer[21], sizeof(U8));
        returnVal->tlm.bootControl = (Boolean)((prepare13 >> 7) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare14;
        MEMCPY(&prepare14, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroConnected = (Boolean)((prepare14 >> 0) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare15;
        MEMCPY(&prepare15, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroTelemetry = (Boolean)((prepare15 >> 1) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare16;
        MEMCPY(&prepare16, &buffer[22], sizeof(U8));
        returnVal->tlm.gyroFlagRegister = (Boolean)((prepare16 >> 2) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare17;
        MEMCPY(&prepare17, &buffer[22], sizeof(U8));
        returnVal->tlm.crcError = (Boolean)((prepare17 >> 3) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare18;
        MEMCPY(&prepare18, &buffer[22], sizeof(U8));
        returnVal->tlm.wrongLlCommand = (Boolean)((prepare18 >> 4) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare19;
        MEMCPY(&prepare19, &buffer[22], sizeof(U8));
        returnVal->tlm.wrongHlCommand = (Boolean)((prepare19 >> 5) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare20;
        MEMCPY(&prepare20, &buffer[22], sizeof(U8));
        returnVal->tlm.toutSci1Main = (Boolean)((prepare20 >> 6) & 0x01);
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        U8 prepare21;
        MEMCPY(&prepare21, &buffer[22], sizeof(U8));
        returnVal->tlm.toutSci2Gyro = (Boolean)((prepare21 >> 7) & 0x01);
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmExtended2(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmExtended2 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 199;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualWheelSpeed, &buffer[1], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmExtended4(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmExtended4 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 200;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 5)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 5)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.actualWheelSpeed, &buffer[1], sizeof(F32));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmSystem2(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmSystem2 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 201;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 23)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 23)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceType, &buffer[1], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceId, &buffer[2], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.month, &buffer[3], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.year, &buffer[4], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.statusRegister, &buffer[5], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsRegister, &buffer[7], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.systemRegister, &buffer[9], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rwaRegister, &buffer[11], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.gyroRegister, &buffer[13], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.bootFlag, &buffer[14], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.bootVector, &buffer[16], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsControlInterval, &buffer[18], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsStartAddr, &buffer[19], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.tachoStartAddr, &buffer[21], sizeof(U16));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNssRwlTlmSystem4(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeControlProgramNssrwlQuad1_NssRwlTlmSystem4 *returnVal)
{
    ErrorCode result = CUBEOBC_ERROR_OK;
    TctlmCommsMasterSvc_Endpoint target;
    U8 *buffer;
    U32 bufferSize;
    U32 bufferSizeUsed;

    ZERO_VAR(target);

    target.id = 202;
    MEMCPY((U8 *)&target.endpoint, (U8 *)endpoint, sizeof(TypeDef_TctlmEndpoint));

    buffer = cubeObc_tctlmCommsMasterSvc_buffer(&target);
    bufferSize = cubeObc_tctlmCommsMasterSvc_bufferSize(&target);

    if (bufferSize < 23)
    {
        result = CUBEOBC_ERROR_SIZEL;
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        bufferSizeUsed = 0;
        result = cubeObc_tctlmCommsMasterSvc_sendReceive(&target, &bufferSizeUsed);
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        if (bufferSizeUsed != 23)
        {
            result = CUBEOBC_ERROR_TLM_SIZE;
        }
    }

    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.serialNumber, &buffer[0], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceType, &buffer[1], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.deviceId, &buffer[2], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.month, &buffer[3], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.year, &buffer[4], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.statusRegister, &buffer[5], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsRegister, &buffer[7], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.systemRegister, &buffer[9], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.rwaRegister, &buffer[11], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.gyroRegister, &buffer[13], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.bootFlag, &buffer[14], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.bootVector, &buffer[16], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsControlInterval, &buffer[18], sizeof(U8));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.acsStartAddr, &buffer[19], sizeof(U16));
    }
    /*************************/
    if (result == CUBEOBC_ERROR_OK)
    {
        MEMCPY(&returnVal->tlm.tachoStartAddr, &buffer[21], sizeof(U16));
    }
    /*************************/

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getNodeModel(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_NodeModel *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_getNodeModel(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getPowerSwitchState(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_PowerSwitchState *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_getPowerSwitchState(endpoint, returnVal);

    return result;
}

ErrorCode tctlmCubeNodeControlProgramNssrwlQuad1_getHealthTlm(TypeDef_TctlmEndpoint *endpoint, TypesCubeNodeCommon1_HealthTlm *returnVal)
{
    ErrorCode result;

    result = tctlmCubeNodeCommon1_getHealthTlm(endpoint, returnVal);

    return result;
}

