/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/

#ifndef TYPES_CUBE_NODE_CONTROL_PROGRAM_PST3S_QUAD_1__H
#define TYPES_CUBE_NODE_CONTROL_PROGRAM_PST3S_QUAD_1__H

#include <cubeObc/cubeObc_typeDef.h>
#include <cubeObc/cubeObc_errorDef.h>
#include <cubeObc/cubeObc_tctlmDef.h>

#include "typesCommonFramework1.h"
#include "typesCubeNodeControlProgramPst3sCommon1.h"
#include "typesCubeNodeCommon1.h"
#include "typesCommonFrameworkTypes1.h"
#include "typesCubeNodeControlProgramPst3sCommonTypes1.h"
#include "typesCubeNodeCommonTypes1.h"

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 *******************************   DEFINES   ***********************************
 ******************************************************************************/

/*******************************************************************************
 *******************************   TYPEDEFS  ***********************************
 ******************************************************************************/

/**
 * @brief PST3S RAW TLM Port 2 message structure
 * @details Get PST3S TLM Packet from port 2. Triggers TLM Request
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sTlm2Struct {
    TypesCubeNodeControlProgramPst3sCommon1_RawTlm tlm;    /**< PST3S raw tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sTlm2;

/**
 * @brief PST3S RAW TLM Port 3 message structure
 * @details Get PST3S TLM Packet from port 3. Triggers TLM Request
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sTlm3Struct {
    TypesCubeNodeControlProgramPst3sCommon1_RawTlm tlm;    /**< PST3S raw tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sTlm3;

/**
 * @brief PST3S RAW TLM Port 4 message structure
 * @details Get PST3S TLM Packet from port 4. Triggers TLM Request
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sTlm4Struct {
    TypesCubeNodeControlProgramPst3sCommon1_RawTlm tlm;    /**< PST3S raw tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sTlm4;

/**
 * @brief PST3S Attitude Data Port 2 message structure
 * @details Get the Last Sampled PST3S Attitude Specific Data from port 2
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sAttitude2Struct {
    TypesCubeNodeControlProgramPst3sCommon1_AttitudeTlm tlm;    /**< PST3S attitude tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sAttitude2;

/**
 * @brief PST3S Attitude Data Port 3 message structure
 * @details Get the Last Sampled PST3S Attitude Specific Data from port 3
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sAttitude3Struct {
    TypesCubeNodeControlProgramPst3sCommon1_AttitudeTlm tlm;    /**< PST3S attitude tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sAttitude3;

/**
 * @brief PST3S Attitude Data Port 4 message structure
 * @details Get the Last Sampled PST3S Attitude Specific Data from port 4
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sAttitude4Struct {
    TypesCubeNodeControlProgramPst3sCommon1_AttitudeTlm tlm;    /**< PST3S attitude tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sAttitude4;

/**
 * @brief PST3S Housekeeping Data Port 2 message structure
 * @details Get the Last Sampled PST3S Housekeeping related data from port 2
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sHousekeeping2Struct {
    TypesCubeNodeControlProgramPst3sCommon1_HousekeepingTlm tlm;    /**< PST3S housekeeping tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sHousekeeping2;

/**
 * @brief PST3S Housekeeping Data Port 3 message structure
 * @details Get the Last Sampled PST3S Housekeeping related data from port 3
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sHousekeeping3Struct {
    TypesCubeNodeControlProgramPst3sCommon1_HousekeepingTlm tlm;    /**< PST3S housekeeping tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sHousekeeping3;

/**
 * @brief PST3S Housekeeping Data Port 4 message structure
 * @details Get the Last Sampled PST3S Housekeeping related data from port 4
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sHousekeeping4Struct {
    TypesCubeNodeControlProgramPst3sCommon1_HousekeepingTlm tlm;    /**< PST3S housekeeping tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sHousekeeping4;

/**
 * @brief PST3S Config Port 2 message structure
 * @details Get the Last Sampled PST3S Config related data from port 2
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sConfig2Struct {
    TypesCubeNodeControlProgramPst3sCommon1_ConfigTlm tlm;    /**< PST3S config tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sConfig2;

/**
 * @brief PST3S Config Port 3 message structure
 * @details Get the Last Sampled PST3S Config related data from port 3
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sConfig3Struct {
    TypesCubeNodeControlProgramPst3sCommon1_ConfigTlm tlm;    /**< PST3S config tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sConfig3;

/**
 * @brief PST3S Config Port 4 message structure
 * @details Get the Last Sampled PST3S Config related data from port 4
 */
typedef struct TCTLM_PACKED TypesCubeNodeControlProgramPst3sQuad1_Pst3sConfig4Struct {
    TypesCubeNodeControlProgramPst3sCommon1_ConfigTlm tlm;    /**< PST3S config tlm  */
} TypesCubeNodeControlProgramPst3sQuad1_Pst3sConfig4;

/*******************************************************************************
 *****************************   PROTOTYPES   **********************************
 ******************************************************************************/

#ifdef __cplusplus
}
#endif

#endif // TYPES_CUBE_NODE_CONTROL_PROGRAM_PST3S_QUAD_1_H
